trigger:
  branches:
    include:
      - main
      - test

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isTest: $[eq(variables['Build.SourceBranch'], 'refs/heads/test')]
  TEST_WEBAPP_NAME: 'web-trialsync-sponsor-platform-test'
  PROD_WEBAPP_NAME: 'web-trialsync-sponsor-platform-prod'
  ARTIFACT_FOLDER: 'sponsor-platform'
  NODE_VERSION: '20'                  # Specify the Node.js version

steps:
  - task: UseNode@1
    inputs:
      version: $(NODE_VERSION)
    displayName: 'Set Node.js version'

  - script: |
      cp $(System.DefaultWorkingDirectory)/production-environment.sample $(System.DefaultWorkingDirectory)/.env.production
    displayName: 'Set up production environment variables'
    condition: eq(variables.isMain, true)
    
  - script: |
      cp $(System.DefaultWorkingDirectory)/development-environment.sample $(System.DefaultWorkingDirectory)/.env.production
    displayName: 'Set up development environment variables'
    condition: eq(variables.isTest, true)

  - script: |
      npm install
      npm run build
      mv ./build/static ./build/standalone/build
      mv ./public ./build/standalone
    displayName: 'Install dependencies and build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'build/standalone'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(ARTIFACT_FOLDER).zip'
      replaceExistingArchive: true
    displayName: 'Archive build output'

  - task: AzureRmWebAppDeployment@4
    condition: eq(variables.isMain, true)
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Microsoft ISV Sponsorship(7644737a-f4e2-4e73-a9f6-957528050d04)'
      appType: 'webAppLinux'
      WebAppName: $(PROD_WEBAPP_NAME)
      packageForLinux: '$(Build.ArtifactStagingDirectory)/$(ARTIFACT_FOLDER).zip'
      RuntimeStack: 'NODE|20-lts'
      StartupCommand: 'node server.js'
  
  - task: AzureRmWebAppDeployment@4
    condition: eq(variables.isTest, true)
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Microsoft ISV Sponsorship(7644737a-f4e2-4e73-a9f6-957528050d04)'
      appType: 'webAppLinux'
      WebAppName: $(TEST_WEBAPP_NAME)
      packageForLinux: '$(Build.ArtifactStagingDirectory)/$(ARTIFACT_FOLDER).zip'
      RuntimeStack: 'NODE|20-lts'
      StartupCommand: 'node server.js'
