trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  WEBAPP_NAME: 'web-trialsync-sponsor-platform-prod'  # Replace with your App Service name
  NODE_VERSION: '20'                  # Specify the Node.js version

steps:
  - task: UseNode@1
    inputs:
      version: $(NODE_VERSION)
    displayName: 'Set Node.js version'

  - script: |
      ls -R
    displayName: 'List files for debugging'
    
  - script: |
      git ls-files
    displayName: 'List tracked files for debugging'

  - script: |
      cp $(System.DefaultWorkingDirectory)/env.production.sample $(System.DefaultWorkingDirectory)/.env.production
    displayName: 'Set up production environment variables'

  - script: |
      npm install
      npm run build
      mv ./build/static ./build/standalone/build
      mv ./public ./build/standalone
    displayName: 'Install dependencies and build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'build/standalone'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(WEBAPP_NAME).zip'
      replaceExistingArchive: true
    displayName: 'Archive build output'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Microsoft ISV Sponsorship(7644737a-f4e2-4e73-a9f6-957528050d04)'
      appType: 'webAppLinux'
      WebAppName: 'web-trialsync-sponsor-platform-prod'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/$(WEBAPP_NAME).zip'
      RuntimeStack: 'NODE|20-lts'
      StartupCommand: 'node server.js'
