trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Archive the build output
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/.next'  # Adjust as needed for your build output
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/webapp.zip'
    replaceExistingArchive: true
  displayName: 'Archive build output'

# Publish the zip file as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/webapp.zip'
    artifactName: 'drop'
    publishLocation: 'Pipeline'

# Deploy using the published artifact directly
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft ISV Sponsorship(7644737a-f4e2-4e73-a9f6-957528050d04)'
    appType: 'webAppLinux'
    WebAppName: 'web-trialsync-sponsor-platform-prod'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/webapp.zip'
    RuntimeStack: 'NODE|20-lts'
