import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from "next/font/google";
import Nav from "@/components/Nav";
// import Provider from "@/components/Provider";

//---- fonts ----
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
});
const satoshi = localFont({
  src: "./fonts/Satoshi-Regular.woff2",
  display: "swap",
  variable: "--font-Satoshi",
});

export const metadata: Metadata = {
  title: "Arash Next.js fullstack app",
  description: "Generated by Arash",
  icons: {
    icon: "/favicon.svg",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${satoshi.variable}`}>
      <body>
        <div className="main">
          <div className="gradient" />
        </div>
        <main className="app">
          <Nav />
          {children}</main>
      </body>
    </html>
  );
}

// <div className="gradient"/> gives a background style
